### ISSUE TITLE
question and feedback

### ISSUE THREAD

**Issue by remb0** [WJ4IoT/Sunscreen#1]
I don't see what you do with:    input_boolean.sunscreen_fake

In the automation you have on line 113: input_boolean.sunscreen_condition
and on line 124 input_boolean.sunscreen_conditions
with and whitout S

**Comment by WJ4IoT** [comment]
As the word says fake; if you do not have a sunscreen (yet) you can use this entity, in other words with a sunscreen you do not need it.

**Comment by remb0** [comment]
not an bad Idea to use it for dry runs.  to gain logging and monitor without actual movements.
