### ISSUE TITLE
vraagje

### ISSUE THREAD

**Issue by remb0** [WJ4IoT/Sunscreen#4]
Ik zie je wijziging op:
sunscreen_criteria en sunscreen_criteria_critical

maar snap hem niet helemaal.  
Deze laat je bestaan en maakt een nieuwe template aan?   of heb je deze vervangen voor de _group varianten?

{{ expand('binary_sensor.sunscreen_criteria_critical_group') | selectattr('state', 'in', ['unavailable', 'unknown', 'none', 'on']) | list | count  > 0 }}

---
Nog even een logica check:
ik heb mijn helpers de naam: set gegeven,   templates entities de naam  Valid
dus de sunscreen_criteria   gaat aan als alles valid is.  met het vinkje: all entities.

en sunscreen_criteria  heeft alle sensors:
sunscreen_criteria_critical  alleen wind en regen (die overruled alles)

klopt mijn gedachtengang?

**Comment by WJ4IoT** [comment]
De stelling is dat als je NIET weet wat de status is van alle groep members je de status van de groep niet kan bepalen en de waarde eigenlijk "UNKNOWN" moet zijn ipv "OFF". Deze situatie komt voor op het moment van een "reload template entities" of een sensor wordt daadwerkelijk "Unavailable" (door bv netwerk of batterij).

Deze alle relevante sensors zijn gegroepeerd in een tweetal groep sensors met _group extentie (oude naam was zonder deze extentie)

Vervolgens worden deze twee group sensors in de nieuwe templates weer ontraffeld en nu de gewenste status bepaald; als een groep member nu "unavailable" is is resultaat van de group On/Unsafe/Problem (Unknown is niet beschikbaar).

Let op: Ik heb gekozen voor zoveel mogelijk de standaard te volgen van HA en hier zit mogelijk ook de bottelneck;  bij de standard is UIT gelijk aan safe/Ok/Dry dus een VALID [(zie)](https://www.home-assistant.io/integrations/binary_sensor/), bij jouw definitie van Valid is deze sensor AAN. 

Jouw "valid" methode zal natuurlijk ook werken inclusief hiervan een group van maken, wellicht is een ontraffelingslag niet eens meer noodzakelijk, de automatisering zal iets moeten worden aangepast, gewenste icons kan je wellicht in de dashboard tweaken met de Mushroom Template Card configuration

**Comment by WJ4IoT** [comment]
Tweede vraag logica check: klopt dus maar pas op je kan ook andere waardes krijgen dan ON/OFF door het vinkje: all entities.

Bij een group sensor kan je een andere groep ook een member laten zijn dus je hoeft zijn vorige members niet te herhalen

In de automatisering is nu critical=Unsafe=On  (dus bij te veel wind/regen) direct uitgevoerd bij non-critical=Safe=Off (dus bij te weinig wind/regen) alleen als geen manual of delay is idle. Omdat bij jouw door de valid=ON dit anderom werkt zijn hier wat kleine aanpassingen noodzakelijk.
